version: "3.9"

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: battlesnake
      MONGO_INITDB_ROOT_PASSWORD: battlesnake
      MONGO_INITDB_DATABASE: battlesnake
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: battlesnake
      ME_CONFIG_MONGODB_ADMINPASSWORD: battlesnake
      ME_CONFIG_MONGODB_URL: mongodb://battlesnake:battlesnake@mongo:27017/

volumes:
  mongo_data:
