[build-system]
requires = ["maturin>=0.13,<0.14"]
build-backend = "maturin"

[project]
version = "0.1.1"
name = "balalaika"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]


